In [296]:
# Global Fuel Price Data set

In [297]:
import pandas as pd
import numpy as np

In [298]:
df = pd.read_csv("fuel_price.csv")

In [299]:
df.head(5)

,date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
0,2020-01-06,United States,North America,High,Low,1.465,1.289,1.093,65.75,59.6
1,2020-01-13,United States,North America,High,Low,1.435,1.319,1.077,65.54,27.6
2,2020-01-20,United States,North America,High,Low,1.446,1.329,1.080,66.51,62.3
3,2020-01-27,United States,North America,High,Low,1.488,1.359,1.125,68.79,44.8
4,2020-02-03,United States,North America,High,Low,1.457,1.341,1.111,68.44,51.4

In [300]:
df.tail(5)

,date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
27463,2026-03-09,Rwanda,Africa,Low,Low,3.036,2.849,2.294,130.0,62.3
27464,2026-03-16,Rwanda,Africa,Low,Low,3.020,2.861,2.248,130.0,43.3
27465,2026-03-23,Rwanda,Africa,Low,Low,3.072,2.825,2.334,130.0,64.1
27466,2026-03-30,Rwanda,Africa,Low,Low,3.045,2.816,2.282,130.0,43.7
27467,2026-04-06,Rwanda,Africa,Low,Low,3.064,2.846,2.296,130.0,63.7

In [301]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              27468 non-null  object
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  object
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), object(5)
memory usage: 2.1+ MB

In [302]:
df.describe

<bound method NDFrame.describe of              date        country         region income_level subsidy_level  \
0      2020-01-06  United States  North America         High           Low
1      2020-01-13  United States  North America         High           Low
2      2020-01-20  United States  North America         High           Low
3      2020-01-27  United States  North America         High           Low
4      2020-02-03  United States  North America         High           Low
...           ...            ...            ...          ...           ...
27463  2026-03-09         Rwanda         Africa          Low           Low
27464  2026-03-16         Rwanda         Africa          Low           Low
27465  2026-03-23         Rwanda         Africa          Low           Low
27466  2026-03-30         Rwanda         Africa          Low           Low
27467  2026-04-06         Rwanda         Africa          Low           Low

       petrol_usd_liter  diesel_usd_liter  lpg_usd_liter  brent_crude_usd  \
0                 1.465             1.289          1.093            65.75
1                 1.435             1.319          1.077            65.54
2                 1.446             1.329          1.080            66.51
3                 1.488             1.359          1.125            68.79
4                 1.457             1.341          1.111            68.44
...                 ...               ...            ...              ...
27463             3.036             2.849          2.294           130.00
27464             3.020             2.861          2.248           130.00
27465             3.072             2.825          2.334           130.00
27466             3.045             2.816          2.282           130.00
27467             3.064             2.846          2.296           130.00

       tax_percentage
0                59.6
1                27.6
2                62.3
3                44.8
4                51.4
...               ...
27463            62.3
27464            43.3
27465            64.1
27466            43.7
27467            63.7

[27468 rows x 10 columns]>

In [303]:
df.describe()

,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
count,27468.000000,27468.000000,27468.000000,27468.000000,27468.000000
mean,2.281915,2.133760,1.711473,106.686453,26.774468
std,1.540612,1.465058,1.155543,18.972391,17.203349
min,0.010000,0.010000,0.010000,47.970000,0.000000
25%,0.926000,0.858000,0.695000,101.140000,13.500000
50%,2.116500,1.954500,1.588000,112.270000,23.400000
75%,3.457000,3.231000,2.590000,119.410000,38.900000
max,6.779000,6.240000,5.100000,130.000000,65.000000

In [304]:
df.count()

date                27468
country             27468
region              27468
income_level        27468
subsidy_level       27468
petrol_usd_liter    27468
diesel_usd_liter    27468
lpg_usd_liter       27468
brent_crude_usd     27468
tax_percentage      27468
dtype: int64

In [305]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              27468 non-null  object
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  object
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), object(5)
memory usage: 2.1+ MB

In [306]:
df.country.count

<bound method Series.count of 0        United States
1        United States
2        United States
3        United States
4        United States
             ...
27463           Rwanda
27464           Rwanda
27465           Rwanda
27466           Rwanda
27467           Rwanda
Name: country, Length: 27468, dtype: object>

In [307]:
df.columns

Index(['date', 'country', 'region', 'income_level', 'subsidy_level',
       'petrol_usd_liter', 'diesel_usd_liter', 'lpg_usd_liter',
       'brent_crude_usd', 'tax_percentage'],
      dtype='object')

In [308]:
df.index

RangeIndex(start=0, stop=27468, step=1)

In [309]:
df["petrol_usd_liter"].max()

6.779

In [310]:
df["country"].unique()

array(['United States', 'Canada', 'Mexico', 'Brazil', 'Argentina',
       'Colombia', 'Chile', 'Peru', 'Venezuela', 'Ecuador',
       'United Kingdom', 'Germany', 'France', 'Italy', 'Spain',
       'Netherlands', 'Belgium', 'Sweden', 'Norway', 'Denmark', 'Finland',
       'Poland', 'Portugal', 'Greece', 'Switzerland', 'Austria',
       'Ireland', 'Hungary', 'Czech Republic', 'Romania', 'Russia',
       'Ukraine', 'Turkey', 'China', 'Japan', 'South Korea', 'India',
       'Indonesia', 'Malaysia', 'Thailand', 'Vietnam', 'Philippines',
       'Bangladesh', 'Pakistan', 'Sri Lanka', 'Nepal', 'Myanmar',
       'Singapore', 'Hong Kong', 'Taiwan', 'Australia', 'New Zealand',
       'Saudi Arabia', 'UAE', 'Kuwait', 'Qatar', 'Iran', 'Iraq', 'Israel',
       'Jordan', 'Lebanon', 'Egypt', 'South Africa', 'Nigeria', 'Kenya',
       'Ethiopia', 'Ghana', 'Tanzania', 'Morocco', 'Algeria', 'Libya',
       'Tunisia', 'Angola', 'Mozambique', 'Zambia', 'Zimbabwe', 'Uganda',
       'Cameroon', 'Senegal', 'Ivory Coast', 'Sudan', 'Botswana',
       'Namibia', 'Rwanda'], dtype=object)

In [311]:
vc = df["country"].value_counts()

print("Top Country:", vc.idxmax())
print("Count:", vc.max())

Top Country: United States
Count: 327

In [312]:
df.isnull().sum()

date                0
country             0
region              0
income_level        0
subsidy_level       0
petrol_usd_liter    0
diesel_usd_liter    0
lpg_usd_liter       0
brent_crude_usd     0
tax_percentage      0
dtype: int64

In [313]:
df.duplicated().sum()

0

In [314]:
df.copy()

,date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
0,2020-01-06,United States,North America,High,Low,1.465,1.289,1.093,65.75,59.6
1,2020-01-13,United States,North America,High,Low,1.435,1.319,1.077,65.54,27.6
2,2020-01-20,United States,North America,High,Low,1.446,1.329,1.080,66.51,62.3
3,2020-01-27,United States,North America,High,Low,1.488,1.359,1.125,68.79,44.8
4,2020-02-03,United States,North America,High,Low,1.457,1.341,1.111,68.44,51.4
...,...,...,...,...,...,...,...,...,...,...
27463,2026-03-09,Rwanda,Africa,Low,Low,3.036,2.849,2.294,130.00,62.3
27464,2026-03-16,Rwanda,Africa,Low,Low,3.020,2.861,2.248,130.00,43.3
27465,2026-03-23,Rwanda,Africa,Low,Low,3.072,2.825,2.334,130.00,64.1
27466,2026-03-30,Rwanda,Africa,Low,Low,3.045,2.816,2.282,130.00,43.7
27467,2026-04-06,Rwanda,Africa,Low,Low,3.064,2.846,2.296,130.00,63.7

In [315]:
df1=df

In [316]:
print(df1)

             date        country         region income_level subsidy_level  \
0      2020-01-06  United States  North America         High           Low
1      2020-01-13  United States  North America         High           Low
2      2020-01-20  United States  North America         High           Low
3      2020-01-27  United States  North America         High           Low
4      2020-02-03  United States  North America         High           Low
...           ...            ...            ...          ...           ...
27463  2026-03-09         Rwanda         Africa          Low           Low
27464  2026-03-16         Rwanda         Africa          Low           Low
27465  2026-03-23         Rwanda         Africa          Low           Low
27466  2026-03-30         Rwanda         Africa          Low           Low
27467  2026-04-06         Rwanda         Africa          Low           Low

       petrol_usd_liter  diesel_usd_liter  lpg_usd_liter  brent_crude_usd  \
0                 1.465             1.289          1.093            65.75
1                 1.435             1.319          1.077            65.54
2                 1.446             1.329          1.080            66.51
3                 1.488             1.359          1.125            68.79
4                 1.457             1.341          1.111            68.44
...                 ...               ...            ...              ...
27463             3.036             2.849          2.294           130.00
27464             3.020             2.861          2.248           130.00
27465             3.072             2.825          2.334           130.00
27466             3.045             2.816          2.282           130.00
27467             3.064             2.846          2.296           130.00

       tax_percentage
0                59.6
1                27.6
2                62.3
3                44.8
4                51.4
...               ...
27463            62.3
27464            43.3
27465            64.1
27466            43.7
27467            63.7

[27468 rows x 10 columns]

In [317]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              27468 non-null  object
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  object
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), object(5)
memory usage: 2.1+ MB

In [318]:
df.loc[5]

date                   2020-02-10
country             United States
region              North America
income_level                 High
subsidy_level                 Low
petrol_usd_liter            1.461
diesel_usd_liter            1.356
lpg_usd_liter               1.105
brent_crude_usd             68.09
tax_percentage               15.0
Name: 5, dtype: object

In [319]:
print(df.loc[0])

date                   2020-01-06
country             United States
region              North America
income_level                 High
subsidy_level                 Low
petrol_usd_liter            1.465
diesel_usd_liter            1.289
lpg_usd_liter               1.093
brent_crude_usd             65.75
tax_percentage               59.6
Name: 0, dtype: object

In [320]:
df.iloc[0]

date                   2020-01-06
country             United States
region              North America
income_level                 High
subsidy_level                 Low
petrol_usd_liter            1.465
diesel_usd_liter            1.289
lpg_usd_liter               1.093
brent_crude_usd             65.75
tax_percentage               59.6
Name: 0, dtype: object

In [321]:
df.iloc[0,3]

'High'

In [322]:
df.info

<bound method DataFrame.info of              date        country         region income_level subsidy_level  \
0      2020-01-06  United States  North America         High           Low
1      2020-01-13  United States  North America         High           Low
2      2020-01-20  United States  North America         High           Low
3      2020-01-27  United States  North America         High           Low
4      2020-02-03  United States  North America         High           Low
...           ...            ...            ...          ...           ...
27463  2026-03-09         Rwanda         Africa          Low           Low
27464  2026-03-16         Rwanda         Africa          Low           Low
27465  2026-03-23         Rwanda         Africa          Low           Low
27466  2026-03-30         Rwanda         Africa          Low           Low
27467  2026-04-06         Rwanda         Africa          Low           Low

       petrol_usd_liter  diesel_usd_liter  lpg_usd_liter  brent_crude_usd  \
0                 1.465             1.289          1.093            65.75
1                 1.435             1.319          1.077            65.54
2                 1.446             1.329          1.080            66.51
3                 1.488             1.359          1.125            68.79
4                 1.457             1.341          1.111            68.44
...                 ...               ...            ...              ...
27463             3.036             2.849          2.294           130.00
27464             3.020             2.861          2.248           130.00
27465             3.072             2.825          2.334           130.00
27466             3.045             2.816          2.282           130.00
27467             3.064             2.846          2.296           130.00

       tax_percentage
0                59.6
1                27.6
2                62.3
3                44.8
4                51.4
...               ...
27463            62.3
27464            43.3
27465            64.1
27466            43.7
27467            63.7

[27468 rows x 10 columns]>

In [323]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              27468 non-null  object
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  object
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), object(5)
memory usage: 2.1+ MB

In [324]:
df1["date"] = pd.to_datetime(df1["date"])

In [325]:
df1["date"]=df1["date"].astype("int64")

In [326]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              27468 non-null  int64
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  object
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), int64(1), object(4)
memory usage: 2.1+ MB

In [327]:
df1["subsidy_level"].unique()

array(['Low', 'High', 'Medium', 'Very High'], dtype=object)

In [328]:
df1["subsidy_level"] = df1["subsidy_level"].map({
    "Low": 1,
    "Medium": 2,
    "High": 3,
    "Very High" : 4
})

In [329]:
# df["subsidy_level"].dtype()

In [330]:
df["subsidy_level"].unique()

array([1, 3, 2, 4], dtype=int64)

In [331]:
df1.sort_values(["income_level","country"])

,date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
16350,1578268800000000000,Australia,Oceania,High,1,2.102,2.017,1.588,65.75,15.2
16351,1578873600000000000,Australia,Oceania,High,1,2.102,1.995,1.590,65.54,51.0
16352,1579478400000000000,Australia,Oceania,High,1,2.186,2.049,1.630,66.51,13.5
16353,1580083200000000000,Australia,Oceania,High,1,2.204,2.125,1.666,68.79,26.1
16354,1580688000000000000,Australia,Oceania,High,1,2.210,2.110,1.664,68.44,26.1
...,...,...,...,...,...,...,...,...,...,...
13402,1773014400000000000,Vietnam,Asia,Middle,2,1.905,1.725,1.419,130.00,28.1
13403,1773619200000000000,Vietnam,Asia,Middle,2,1.853,1.720,1.400,130.00,15.5
13404,1774224000000000000,Vietnam,Asia,Middle,2,1.892,1.677,1.418,130.00,13.1
13405,1774828800000000000,Vietnam,Asia,Middle,2,1.864,1.724,1.390,130.00,18.4
13406,1775433600000000000,Vietnam,Asia,Middle,2,1.916,1.713,1.456,130.00,6.9

In [332]:
df1.sort_index()

,date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
0,1578268800000000000,United States,North America,High,1,1.465,1.289,1.093,65.75,59.6
1,1578873600000000000,United States,North America,High,1,1.435,1.319,1.077,65.54,27.6
2,1579478400000000000,United States,North America,High,1,1.446,1.329,1.080,66.51,62.3
3,1580083200000000000,United States,North America,High,1,1.488,1.359,1.125,68.79,44.8
4,1580688000000000000,United States,North America,High,1,1.457,1.341,1.111,68.44,51.4
...,...,...,...,...,...,...,...,...,...,...
27463,1773014400000000000,Rwanda,Africa,Low,1,3.036,2.849,2.294,130.00,62.3
27464,1773619200000000000,Rwanda,Africa,Low,1,3.020,2.861,2.248,130.00,43.3
27465,1774224000000000000,Rwanda,Africa,Low,1,3.072,2.825,2.334,130.00,64.1
27466,1774828800000000000,Rwanda,Africa,Low,1,3.045,2.816,2.282,130.00,43.7
27467,1775433600000000000,Rwanda,Africa,Low,1,3.064,2.846,2.296,130.00,63.7

In [333]:
df1.rename(columns={"date": "Date"}, inplace=True)

In [334]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              27468 non-null  int64
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  int64
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), int64(2), object(3)
memory usage: 2.1+ MB

In [335]:
# df1 = df1[["country" , "Date" , "income_level"]]

In [336]:
# df1.info()

In [337]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              27468 non-null  int64
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  int64
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), int64(2), object(3)
memory usage: 2.1+ MB

In [338]:
df1_backup = df1.copy()

In [339]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              27468 non-null  int64
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  int64
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), int64(2), object(3)
memory usage: 2.1+ MB

In [340]:
# df1_backup.info()

In [341]:
df["subsidy_level"].values

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [342]:
df1.columns

Index(['Date', 'country', 'region', 'income_level', 'subsidy_level',
       'petrol_usd_liter', 'diesel_usd_liter', 'lpg_usd_liter',
       'brent_crude_usd', 'tax_percentage'],
      dtype='object')

In [343]:
df.dropna(subset=["Date"])

,Date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
0,1578268800000000000,United States,North America,High,1,1.465,1.289,1.093,65.75,59.6
1,1578873600000000000,United States,North America,High,1,1.435,1.319,1.077,65.54,27.6
2,1579478400000000000,United States,North America,High,1,1.446,1.329,1.080,66.51,62.3
3,1580083200000000000,United States,North America,High,1,1.488,1.359,1.125,68.79,44.8
4,1580688000000000000,United States,North America,High,1,1.457,1.341,1.111,68.44,51.4
...,...,...,...,...,...,...,...,...,...,...
27463,1773014400000000000,Rwanda,Africa,Low,1,3.036,2.849,2.294,130.00,62.3
27464,1773619200000000000,Rwanda,Africa,Low,1,3.020,2.861,2.248,130.00,43.3
27465,1774224000000000000,Rwanda,Africa,Low,1,3.072,2.825,2.334,130.00,64.1
27466,1774828800000000000,Rwanda,Africa,Low,1,3.045,2.816,2.282,130.00,43.7
27467,1775433600000000000,Rwanda,Africa,Low,1,3.064,2.846,2.296,130.00,63.7

In [344]:
df1 = df1.drop(["subsidy_level", "Date"], axis=1)

In [345]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   country           27468 non-null  object
 1   region            27468 non-null  object
 2   income_level      27468 non-null  object
 3   petrol_usd_liter  27468 non-null  float64
 4   diesel_usd_liter  27468 non-null  float64
 5   lpg_usd_liter     27468 non-null  float64
 6   brent_crude_usd   27468 non-null  float64
 7   tax_percentage    27468 non-null  float64
dtypes: float64(5), object(3)
memory usage: 1.7+ MB

In [346]:
# df1=df1.melt(id_vars=["Name"],value_vars=["math","science","English"],var_name="subject",value_name="score")

In [347]:
# df.pivot(index=None, columns=None, values=None )